/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface BokkyPooBahsDateTimeLibrary extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): BokkyPooBahsDateTimeLibrary;
  clone(): BokkyPooBahsDateTimeLibrary;
  methods: {
    DOW_FRI(): NonPayableTransactionObject<string>;

    DOW_MON(): NonPayableTransactionObject<string>;

    DOW_SAT(): NonPayableTransactionObject<string>;

    DOW_SUN(): NonPayableTransactionObject<string>;

    DOW_THU(): NonPayableTransactionObject<string>;

    DOW_TUE(): NonPayableTransactionObject<string>;

    DOW_WED(): NonPayableTransactionObject<string>;

    OFFSET19700101(): NonPayableTransactionObject<string>;

    SECONDS_PER_DAY(): NonPayableTransactionObject<string>;

    SECONDS_PER_HOUR(): NonPayableTransactionObject<string>;

    SECONDS_PER_MINUTE(): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
