/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface CheckPointHistoryMock extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): CheckPointHistoryMock;
  clone(): CheckPointHistoryMock;
  methods: {
    cleanupOldCheckpoints(
      _count: number | string | BN,
      _cleanupBlockNumber: number | string | BN
    ): NonPayableTransactionObject<void>;

    valueAt(
      _blockNumber: number | string | BN
    ): NonPayableTransactionObject<string>;

    valueAtNow(): NonPayableTransactionObject<string>;

    writeValue(_value: number | string | BN): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
