/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface CheckPointsByAddressMock extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): CheckPointsByAddressMock;
  clone(): CheckPointsByAddressMock;
  methods: {
    cleanupOldCheckpoints(
      _owner: string,
      _count: number | string | BN,
      _cleanupBlockNumber: number | string | BN
    ): NonPayableTransactionObject<void>;

    transmit(
      _from: string,
      _to: string,
      _amount: number | string | BN
    ): NonPayableTransactionObject<void>;

    valueOfAt(
      _owner: string,
      _blockNumber: number | string | BN
    ): NonPayableTransactionObject<string>;

    valueOfAtNow(_owner: string): NonPayableTransactionObject<string>;

    writeValue(
      _owner: string,
      _value: number | string | BN
    ): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
