/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type AccountClaimed = ContractEventLog<{
  theAccount: string;
  0: string;
}>;
export type AccountOptOut = ContractEventLog<{
  theAccount: string;
  0: string;
}>;
export type AccountsAdded = ContractEventLog<{
  accountsArray: string[];
  0: string[];
}>;
export type EntitlementStarted = ContractEventLog<{}>;
export type GovernanceProposed = ContractEventLog<{
  proposedGovernance: string;
  0: string;
}>;
export type GovernanceUpdated = ContractEventLog<{
  oldGovernance: string;
  newGoveranance: string;
  0: string;
  1: string;
}>;
export type OptOutWeiWithdrawn = ContractEventLog<{}>;

export interface Distribution extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): Distribution;
  clone(): Distribution;
  methods: {
    airdropAccounts(arg0: string): NonPayableTransactionObject<{
      entitlementBalanceWei: string;
      totalClaimedWei: string;
      optOutBalanceWei: string;
      airdroppedAtGenesisWei: string;
      0: string;
      1: string;
      2: string;
      3: string;
    }>;

    claim(_recipient: string): NonPayableTransactionObject<string>;

    claimGovernance(): NonPayableTransactionObject<void>;

    entitlementStartTs(): NonPayableTransactionObject<string>;

    getClaimableAmount(): NonPayableTransactionObject<string>;

    getClaimableAmountOf(account: string): NonPayableTransactionObject<string>;

    getTokenPoolSupplyData(): NonPayableTransactionObject<{
      _lockedFundsWei: string;
      _totalInflationAuthorizedWei: string;
      _totalClaimedWei: string;
      0: string;
      1: string;
      2: string;
    }>;

    governance(): NonPayableTransactionObject<string>;

    initialise(_governance: string): NonPayableTransactionObject<void>;

    optOutOfAirdrop(): NonPayableTransactionObject<void>;

    proposeGovernance(_governance: string): NonPayableTransactionObject<void>;

    proposedGovernance(): NonPayableTransactionObject<string>;

    secondsTillNextClaim(): NonPayableTransactionObject<string>;

    setClaimBalance(
      toAddress: string[],
      balance: (number | string | BN)[]
    ): NonPayableTransactionObject<void>;

    setEntitlementStart(
      _entitlementStartTs: number | string | BN
    ): NonPayableTransactionObject<void>;

    totalClaimedWei(): NonPayableTransactionObject<string>;

    totalEntitlementWei(): NonPayableTransactionObject<string>;

    totalOptOutWei(): NonPayableTransactionObject<string>;

    transferGovernance(_governance: string): NonPayableTransactionObject<void>;

    treasury(): NonPayableTransactionObject<string>;

    withdrawOptOutWei(
      _targetAddress: string
    ): NonPayableTransactionObject<string>;

    withdrawnOptOutWei(): NonPayableTransactionObject<string>;
  };
  events: {
    AccountClaimed(cb?: Callback<AccountClaimed>): EventEmitter;
    AccountClaimed(
      options?: EventOptions,
      cb?: Callback<AccountClaimed>
    ): EventEmitter;

    AccountOptOut(cb?: Callback<AccountOptOut>): EventEmitter;
    AccountOptOut(
      options?: EventOptions,
      cb?: Callback<AccountOptOut>
    ): EventEmitter;

    AccountsAdded(cb?: Callback<AccountsAdded>): EventEmitter;
    AccountsAdded(
      options?: EventOptions,
      cb?: Callback<AccountsAdded>
    ): EventEmitter;

    EntitlementStarted(cb?: Callback<EntitlementStarted>): EventEmitter;
    EntitlementStarted(
      options?: EventOptions,
      cb?: Callback<EntitlementStarted>
    ): EventEmitter;

    GovernanceProposed(cb?: Callback<GovernanceProposed>): EventEmitter;
    GovernanceProposed(
      options?: EventOptions,
      cb?: Callback<GovernanceProposed>
    ): EventEmitter;

    GovernanceUpdated(cb?: Callback<GovernanceUpdated>): EventEmitter;
    GovernanceUpdated(
      options?: EventOptions,
      cb?: Callback<GovernanceUpdated>
    ): EventEmitter;

    OptOutWeiWithdrawn(cb?: Callback<OptOutWeiWithdrawn>): EventEmitter;
    OptOutWeiWithdrawn(
      options?: EventOptions,
      cb?: Callback<OptOutWeiWithdrawn>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "AccountClaimed", cb: Callback<AccountClaimed>): void;
  once(
    event: "AccountClaimed",
    options: EventOptions,
    cb: Callback<AccountClaimed>
  ): void;

  once(event: "AccountOptOut", cb: Callback<AccountOptOut>): void;
  once(
    event: "AccountOptOut",
    options: EventOptions,
    cb: Callback<AccountOptOut>
  ): void;

  once(event: "AccountsAdded", cb: Callback<AccountsAdded>): void;
  once(
    event: "AccountsAdded",
    options: EventOptions,
    cb: Callback<AccountsAdded>
  ): void;

  once(event: "EntitlementStarted", cb: Callback<EntitlementStarted>): void;
  once(
    event: "EntitlementStarted",
    options: EventOptions,
    cb: Callback<EntitlementStarted>
  ): void;

  once(event: "GovernanceProposed", cb: Callback<GovernanceProposed>): void;
  once(
    event: "GovernanceProposed",
    options: EventOptions,
    cb: Callback<GovernanceProposed>
  ): void;

  once(event: "GovernanceUpdated", cb: Callback<GovernanceUpdated>): void;
  once(
    event: "GovernanceUpdated",
    options: EventOptions,
    cb: Callback<GovernanceUpdated>
  ): void;

  once(event: "OptOutWeiWithdrawn", cb: Callback<OptOutWeiWithdrawn>): void;
  once(
    event: "OptOutWeiWithdrawn",
    options: EventOptions,
    cb: Callback<OptOutWeiWithdrawn>
  ): void;
}
