/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface ExplicitDelegationMock extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): ExplicitDelegationMock;
  clone(): ExplicitDelegationMock;
  methods: {
    addReplaceDelegate(
      _delegate: string,
      _bips: number | string | BN
    ): NonPayableTransactionObject<void>;

    cleanupOldCheckpoints(
      _delegate: string,
      _count: number | string | BN,
      _cleanupBlockNumber: number | string | BN
    ): NonPayableTransactionObject<void>;

    getDelegatedTotal(): NonPayableTransactionObject<string>;

    getDelegatedTotalAt(
      _blockNumber: number | string | BN
    ): NonPayableTransactionObject<string>;

    getDelegatedValue(_delegate: string): NonPayableTransactionObject<string>;

    getDelegatedValueAt(
      _delegate: string,
      _blockNumber: number | string | BN
    ): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
