/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface FiniteLoopMock extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): FiniteLoopMock;
  clone(): FiniteLoopMock;
  methods: {
    arr(arg0: number | string | BN): NonPayableTransactionObject<string>;

    daemonize(): NonPayableTransactionObject<boolean>;

    getContractName(): NonPayableTransactionObject<string>;

    length(): NonPayableTransactionObject<string>;

    numLoop(): NonPayableTransactionObject<string>;

    setLoopParameter(
      n: number | string | BN
    ): NonPayableTransactionObject<void>;

    setWhichBlocks(n: number | string | BN): NonPayableTransactionObject<void>;

    switchToFallbackMode(): NonPayableTransactionObject<boolean>;

    whichBlock(): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
