/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface FtsoVoteMock extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): FtsoVoteMock;
  clone(): FtsoVoteMock;
  methods: {
    createInstance(
      _voter: string,
      _votePowerNat: number | string | BN,
      _votePowerAsset: number | string | BN,
      _totalVotePowerNat: number | string | BN,
      _totalVotePowerAsset: number | string | BN,
      _price: number | string | BN
    ): NonPayableTransactionObject<[string, string, string, string, string]>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
