/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface InflationMock1 extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): InflationMock1;
  clone(): InflationMock1;
  methods: {
    DEFAULT_FALLBACK_VALUE(): NonPayableTransactionObject<string>;

    MOCKS_LIST_END(): NonPayableTransactionObject<string>;

    MOCKS_LIST_END_HASH(): NonPayableTransactionObject<string>;

    MOCKS_LIST_START(): NonPayableTransactionObject<string>;

    SENTINEL_ANY_MOCKS(): NonPayableTransactionObject<string>;

    doNotReceiveMoreThan(): NonPayableTransactionObject<string>;

    givenAnyReturn(
      response: string | number[]
    ): NonPayableTransactionObject<void>;

    givenAnyReturnAddress(response: string): NonPayableTransactionObject<void>;

    givenAnyReturnBool(response: boolean): NonPayableTransactionObject<void>;

    givenAnyReturnUint(
      response: number | string | BN
    ): NonPayableTransactionObject<void>;

    givenAnyRevert(): NonPayableTransactionObject<void>;

    givenAnyRevertWithMessage(
      message: string
    ): NonPayableTransactionObject<void>;

    givenAnyRunOutOfGas(): NonPayableTransactionObject<void>;

    givenCalldataReturn(
      call: string | number[],
      response: string | number[]
    ): NonPayableTransactionObject<void>;

    givenCalldataReturnAddress(
      call: string | number[],
      response: string
    ): NonPayableTransactionObject<void>;

    givenCalldataReturnBool(
      call: string | number[],
      response: boolean
    ): NonPayableTransactionObject<void>;

    givenCalldataReturnUint(
      call: string | number[],
      response: number | string | BN
    ): NonPayableTransactionObject<void>;

    givenCalldataRevert(
      call: string | number[]
    ): NonPayableTransactionObject<void>;

    givenCalldataRevertWithMessage(
      call: string | number[],
      message: string
    ): NonPayableTransactionObject<void>;

    givenCalldataRunOutOfGas(
      call: string | number[]
    ): NonPayableTransactionObject<void>;

    givenMethodReturn(
      call: string | number[],
      response: string | number[]
    ): NonPayableTransactionObject<void>;

    givenMethodReturnAddress(
      call: string | number[],
      response: string
    ): NonPayableTransactionObject<void>;

    givenMethodReturnBool(
      call: string | number[],
      response: boolean
    ): NonPayableTransactionObject<void>;

    givenMethodReturnUint(
      call: string | number[],
      response: number | string | BN
    ): NonPayableTransactionObject<void>;

    givenMethodRevert(
      call: string | number[]
    ): NonPayableTransactionObject<void>;

    givenMethodRevertWithMessage(
      call: string | number[],
      message: string
    ): NonPayableTransactionObject<void>;

    givenMethodRunOutOfGas(
      call: string | number[]
    ): NonPayableTransactionObject<void>;

    invocationCount(): NonPayableTransactionObject<string>;

    invocationCountForCalldata(
      call: string | number[]
    ): NonPayableTransactionObject<string>;

    invocationCountForMethod(
      call: string | number[]
    ): NonPayableTransactionObject<string>;

    receiveInflation(): PayableTransactionObject<void>;

    receiveMinting(): PayableTransactionObject<void>;

    requestMinting(
      amount: number | string | BN
    ): NonPayableTransactionObject<void>;

    reset(): NonPayableTransactionObject<void>;

    setDailyAuthorizedInflation(
      toAuthorizeWei: number | string | BN
    ): NonPayableTransactionObject<void>;

    setDoNotReceiveNoMoreThan(
      _doNotReceiveMoreThan: number | string | BN
    ): NonPayableTransactionObject<void>;

    setFlareDaemon(_flareDaemon: string): NonPayableTransactionObject<void>;

    setInflationReceiver(
      _inflationReceiver: string
    ): NonPayableTransactionObject<void>;

    tick(): NonPayableTransactionObject<void>;

    ticker(): NonPayableTransactionObject<string>;

    updateInvocationCount(
      methodId: string | number[],
      originalMsgData: string | number[]
    ): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
