/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type DailyAuthorizedInflationSet = ContractEventLog<{
  authorizedAmountWei: string;
  0: string;
}>;
export type FoundationAllocatedFundsReceived = ContractEventLog<{
  amountReceivedWei: string;
  0: string;
}>;
export type GovernanceProposed = ContractEventLog<{
  proposedGovernance: string;
  0: string;
}>;
export type GovernanceUpdated = ContractEventLog<{
  oldGovernance: string;
  newGoveranance: string;
  0: string;
  1: string;
}>;
export type InflationReceived = ContractEventLog<{
  amountReceivedWei: string;
  0: string;
}>;

export interface InflationReceiverAndTokenPoolMock extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): InflationReceiverAndTokenPoolMock;
  clone(): InflationReceiverAndTokenPoolMock;
  methods: {
    claimGovernance(): NonPayableTransactionObject<void>;

    claimMock(
      _recipient: string,
      _rewardAmount: number | string | BN
    ): NonPayableTransactionObject<void>;

    dailyAuthorizedInflation(): NonPayableTransactionObject<string>;

    foundationAllocatedFundsWei(): NonPayableTransactionObject<string>;

    getContractName(): NonPayableTransactionObject<string>;

    getInflationAddress(): NonPayableTransactionObject<string>;

    getTokenPoolSupplyData(): NonPayableTransactionObject<{
      _foundationAllocatedFundsWei: string;
      _totalInflationAuthorizedWei: string;
      _totalClaimedWei: string;
      0: string;
      1: string;
      2: string;
    }>;

    governance(): NonPayableTransactionObject<string>;

    inflation(): NonPayableTransactionObject<string>;

    initialise(_governance: string): NonPayableTransactionObject<void>;

    lastInflationAuthorizationReceivedTs(): NonPayableTransactionObject<string>;

    proposeGovernance(_governance: string): NonPayableTransactionObject<void>;

    proposedGovernance(): NonPayableTransactionObject<string>;

    receiveFoundationAllocatedFunds(): PayableTransactionObject<void>;

    receiveInflation(): PayableTransactionObject<void>;

    setDailyAuthorizedInflation(
      _toAuthorizeWei: number | string | BN
    ): NonPayableTransactionObject<void>;

    totalClaimedWei(): NonPayableTransactionObject<string>;

    totalInflationAuthorizedWei(): NonPayableTransactionObject<string>;

    totalInflationReceivedWei(): NonPayableTransactionObject<string>;

    totalSelfDestructReceivedWei(): NonPayableTransactionObject<string>;

    transferGovernance(_governance: string): NonPayableTransactionObject<void>;
  };
  events: {
    DailyAuthorizedInflationSet(
      cb?: Callback<DailyAuthorizedInflationSet>
    ): EventEmitter;
    DailyAuthorizedInflationSet(
      options?: EventOptions,
      cb?: Callback<DailyAuthorizedInflationSet>
    ): EventEmitter;

    FoundationAllocatedFundsReceived(
      cb?: Callback<FoundationAllocatedFundsReceived>
    ): EventEmitter;
    FoundationAllocatedFundsReceived(
      options?: EventOptions,
      cb?: Callback<FoundationAllocatedFundsReceived>
    ): EventEmitter;

    GovernanceProposed(cb?: Callback<GovernanceProposed>): EventEmitter;
    GovernanceProposed(
      options?: EventOptions,
      cb?: Callback<GovernanceProposed>
    ): EventEmitter;

    GovernanceUpdated(cb?: Callback<GovernanceUpdated>): EventEmitter;
    GovernanceUpdated(
      options?: EventOptions,
      cb?: Callback<GovernanceUpdated>
    ): EventEmitter;

    InflationReceived(cb?: Callback<InflationReceived>): EventEmitter;
    InflationReceived(
      options?: EventOptions,
      cb?: Callback<InflationReceived>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(
    event: "DailyAuthorizedInflationSet",
    cb: Callback<DailyAuthorizedInflationSet>
  ): void;
  once(
    event: "DailyAuthorizedInflationSet",
    options: EventOptions,
    cb: Callback<DailyAuthorizedInflationSet>
  ): void;

  once(
    event: "FoundationAllocatedFundsReceived",
    cb: Callback<FoundationAllocatedFundsReceived>
  ): void;
  once(
    event: "FoundationAllocatedFundsReceived",
    options: EventOptions,
    cb: Callback<FoundationAllocatedFundsReceived>
  ): void;

  once(event: "GovernanceProposed", cb: Callback<GovernanceProposed>): void;
  once(
    event: "GovernanceProposed",
    options: EventOptions,
    cb: Callback<GovernanceProposed>
  ): void;

  once(event: "GovernanceUpdated", cb: Callback<GovernanceUpdated>): void;
  once(
    event: "GovernanceUpdated",
    options: EventOptions,
    cb: Callback<GovernanceUpdated>
  ): void;

  once(event: "InflationReceived", cb: Callback<InflationReceived>): void;
  once(
    event: "InflationReceived",
    options: EventOptions,
    cb: Callback<InflationReceived>
  ): void;
}
