/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface PercentageDelegationMock extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): PercentageDelegationMock;
  clone(): PercentageDelegationMock;
  methods: {
    addReplaceDelegate(
      _delegate: string,
      _bips: number | string | BN
    ): NonPayableTransactionObject<void>;

    addReplaceMultipleDelegates(
      _delegates: string[],
      _bipss: (number | string | BN)[]
    ): NonPayableTransactionObject<void>;

    cleanupOldCheckpoints(
      _count: number | string | BN,
      _cleanupBlockNumber: number | string | BN
    ): NonPayableTransactionObject<void>;

    clear(): NonPayableTransactionObject<void>;

    getCount(): NonPayableTransactionObject<string>;

    getCountAt(
      _blockNumber: number | string | BN
    ): NonPayableTransactionObject<string>;

    getDelegatedTotal(): NonPayableTransactionObject<string>;

    getDelegatedTotalAt(
      _blockNumber: number | string | BN
    ): NonPayableTransactionObject<string>;

    getDelegatedValue(_delegate: string): NonPayableTransactionObject<string>;

    getDelegatedValueAt(
      _delegate: string,
      _blockNumber: number | string | BN
    ): NonPayableTransactionObject<string>;

    getDelegations(): NonPayableTransactionObject<{
      _delegates: string[];
      _values: string[];
      0: string[];
      1: string[];
    }>;

    getDelegationsAt(
      _blockNumber: number | string | BN
    ): NonPayableTransactionObject<{
      _delegates: string[];
      _values: string[];
      0: string[];
      1: string[];
    }>;

    getDelegationsRaw(): NonPayableTransactionObject<[string, string][]>;

    maxDelegateCount(): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
