/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type GovernanceProposed = ContractEventLog<{
  proposedGovernance: string;
  0: string;
}>;
export type GovernanceUpdated = ContractEventLog<{
  oldGovernance: string;
  newGoveranance: string;
  0: string;
  1: string;
}>;
export type HashSubmitted = ContractEventLog<{
  submitter: string;
  epochId: string;
  hash: string;
  timestamp: string;
  0: string;
  1: string;
  2: string;
  3: string;
}>;
export type PricesRevealed = ContractEventLog<{
  voter: string;
  epochId: string;
  ftsos: string[];
  prices: string[];
  random: string;
  timestamp: string;
  0: string;
  1: string;
  2: string[];
  3: string[];
  4: string;
  5: string;
}>;

export interface PriceSubmitter extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): PriceSubmitter;
  clone(): PriceSubmitter;
  methods: {
    MINIMAL_RANDOM(): NonPayableTransactionObject<string>;

    RANDOM_EPOCH_CYCLIC_BUFFER_SIZE(): NonPayableTransactionObject<string>;

    claimGovernance(): NonPayableTransactionObject<void>;

    getAddressUpdater(): NonPayableTransactionObject<string>;

    getCurrentRandom(): NonPayableTransactionObject<string>;

    getFtsoManager(): NonPayableTransactionObject<string>;

    getFtsoRegistry(): NonPayableTransactionObject<string>;

    getRandom(
      _epochId: number | string | BN
    ): NonPayableTransactionObject<string>;

    getTrustedAddresses(): NonPayableTransactionObject<string[]>;

    getVoterWhitelister(): NonPayableTransactionObject<string>;

    governance(): NonPayableTransactionObject<string>;

    initialise(_governance: string): NonPayableTransactionObject<void>;

    initialiseFixedAddress(): NonPayableTransactionObject<string>;

    proposeGovernance(_governance: string): NonPayableTransactionObject<void>;

    proposedGovernance(): NonPayableTransactionObject<string>;

    revealPrices(
      _epochId: number | string | BN,
      _ftsoIndices: (number | string | BN)[],
      _prices: (number | string | BN)[],
      _random: number | string | BN
    ): NonPayableTransactionObject<void>;

    setAddressUpdater(
      _addressUpdater: string
    ): NonPayableTransactionObject<void>;

    setTrustedAddresses(
      _trustedAddresses: string[]
    ): NonPayableTransactionObject<void>;

    submitHash(
      _epochId: number | string | BN,
      _hash: string | number[]
    ): NonPayableTransactionObject<void>;

    transferGovernance(_governance: string): NonPayableTransactionObject<void>;

    updateContractAddresses(
      _contractNameHashes: (string | number[])[],
      _contractAddresses: string[]
    ): NonPayableTransactionObject<void>;

    voterWhitelistBitmap(_voter: string): NonPayableTransactionObject<string>;

    voterWhitelisted(
      _voter: string,
      _ftsoIndex: number | string | BN
    ): NonPayableTransactionObject<void>;

    votersRemovedFromWhitelist(
      _removedVoters: string[],
      _ftsoIndex: number | string | BN
    ): NonPayableTransactionObject<void>;
  };
  events: {
    GovernanceProposed(cb?: Callback<GovernanceProposed>): EventEmitter;
    GovernanceProposed(
      options?: EventOptions,
      cb?: Callback<GovernanceProposed>
    ): EventEmitter;

    GovernanceUpdated(cb?: Callback<GovernanceUpdated>): EventEmitter;
    GovernanceUpdated(
      options?: EventOptions,
      cb?: Callback<GovernanceUpdated>
    ): EventEmitter;

    HashSubmitted(cb?: Callback<HashSubmitted>): EventEmitter;
    HashSubmitted(
      options?: EventOptions,
      cb?: Callback<HashSubmitted>
    ): EventEmitter;

    PricesRevealed(cb?: Callback<PricesRevealed>): EventEmitter;
    PricesRevealed(
      options?: EventOptions,
      cb?: Callback<PricesRevealed>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "GovernanceProposed", cb: Callback<GovernanceProposed>): void;
  once(
    event: "GovernanceProposed",
    options: EventOptions,
    cb: Callback<GovernanceProposed>
  ): void;

  once(event: "GovernanceUpdated", cb: Callback<GovernanceUpdated>): void;
  once(
    event: "GovernanceUpdated",
    options: EventOptions,
    cb: Callback<GovernanceUpdated>
  ): void;

  once(event: "HashSubmitted", cb: Callback<HashSubmitted>): void;
  once(
    event: "HashSubmitted",
    options: EventOptions,
    cb: Callback<HashSubmitted>
  ): void;

  once(event: "PricesRevealed", cb: Callback<PricesRevealed>): void;
  once(
    event: "PricesRevealed",
    options: EventOptions,
    cb: Callback<PricesRevealed>
  ): void;
}
