/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type GovernanceProposed = ContractEventLog<{
  proposedGovernance: string;
  0: string;
}>;
export type GovernanceUpdated = ContractEventLog<{
  oldGovernance: string;
  newGoveranance: string;
  0: string;
  1: string;
}>;

export interface TeamEscrow extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): TeamEscrow;
  clone(): TeamEscrow;
  methods: {
    DIRECT_CLAIM_BIPS(): NonPayableTransactionObject<string>;

    FULL_CLAIM_BIPS(): NonPayableTransactionObject<string>;

    LOCKED_CLAIM_BIPS(): NonPayableTransactionObject<string>;

    claim(): NonPayableTransactionObject<void>;

    claimGovernance(): NonPayableTransactionObject<void>;

    claimStartTs(): NonPayableTransactionObject<string>;

    claimTo(_target: string): NonPayableTransactionObject<void>;

    getCurrentClaimablePercentBips(
      _timestamp: number | string | BN
    ): NonPayableTransactionObject<string>;

    getCurrentClaimableWei(_owner: string): NonPayableTransactionObject<string>;

    getTokenPoolSupplyData(): NonPayableTransactionObject<{
      _lockedFundsWei: string;
      _totalInflationAuthorizedWei: string;
      _totalClaimedWei: string;
      0: string;
      1: string;
      2: string;
    }>;

    governance(): NonPayableTransactionObject<string>;

    governanceChangedClaimTs(): NonPayableTransactionObject<boolean>;

    initialise(_governance: string): NonPayableTransactionObject<void>;

    lock(): PayableTransactionObject<void>;

    lockedAmounts(arg0: string): NonPayableTransactionObject<{
      totalLockedAmountWei: string;
      totalClaimedAmountWei: string;
      0: string;
      1: string;
    }>;

    proposeGovernance(_governance: string): NonPayableTransactionObject<void>;

    proposedGovernance(): NonPayableTransactionObject<string>;

    setClaimingStartTs(
      _claimStartTs: number | string | BN
    ): NonPayableTransactionObject<void>;

    totalClaimedAmountWei(): NonPayableTransactionObject<string>;

    totalLockedAmountWei(): NonPayableTransactionObject<string>;

    transferGovernance(_governance: string): NonPayableTransactionObject<void>;
  };
  events: {
    GovernanceProposed(cb?: Callback<GovernanceProposed>): EventEmitter;
    GovernanceProposed(
      options?: EventOptions,
      cb?: Callback<GovernanceProposed>
    ): EventEmitter;

    GovernanceUpdated(cb?: Callback<GovernanceUpdated>): EventEmitter;
    GovernanceUpdated(
      options?: EventOptions,
      cb?: Callback<GovernanceUpdated>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "GovernanceProposed", cb: Callback<GovernanceProposed>): void;
  once(
    event: "GovernanceProposed",
    options: EventOptions,
    cb: Callback<GovernanceProposed>
  ): void;

  once(event: "GovernanceUpdated", cb: Callback<GovernanceUpdated>): void;
  once(
    event: "GovernanceUpdated",
    options: EventOptions,
    cb: Callback<GovernanceUpdated>
  ): void;
}
