/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface VotePowerMock extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): VotePowerMock;
  clone(): VotePowerMock;
  methods: {
    _burn(
      _owner: string,
      _amount: number | string | BN
    ): NonPayableTransactionObject<void>;

    _mint(
      _owner: string,
      _amount: number | string | BN
    ): NonPayableTransactionObject<void>;

    cleanupOldCheckpoints(
      _owner: string,
      _count: number | string | BN,
      _cleanupBlockNumber: number | string | BN
    ): NonPayableTransactionObject<void>;

    delegate(
      _delegator: string,
      _delegatee: string,
      _amount: number | string | BN
    ): NonPayableTransactionObject<void>;

    transmit(
      _from: string,
      _to: string,
      _amount: number | string | BN
    ): NonPayableTransactionObject<void>;

    undelegate(
      _delegator: string,
      _delegatee: string,
      _amount: number | string | BN
    ): NonPayableTransactionObject<void>;

    votePowerOfAt(
      _who: string,
      _blockNumber: number | string | BN
    ): NonPayableTransactionObject<string>;

    votePowerOfAtNow(_who: string): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
